# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=20)),
                ('lastName', models.TextField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='birthdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BirthdayApp.User'),
        ),
    ]
