# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BirthdayApp', '0002_auto_20160614_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BirthdayApp.Birthdate'),
        ),
    ]
