# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BirthdayApp', '0004_auto_20160622_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='BirthdayApp.Birthdate', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.TextField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.TextField(max_length=30, verbose_name='Last Name'),
        ),
    ]
