# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=20, verbose_name='First Name')),
                ('last_name', models.TextField(max_length=30, verbose_name='Last Name')),
                ('date_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday_app.Birthdate', verbose_name='Date of Birth')),
            ],
        ),
    ]
