# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0002_auto_20160805_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.DeleteModel(
            name='Birthdate',
        ),
    ]
